OnlineStore/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineStore;

namespace OnlineStore.Controllers
{
    public class CategorySetUpController : Controller
    {
        private OnlineStoreEntities db = new OnlineStoreEntities();

        // GET: Category
        public ActionResult ShowList()
        {
             object CategoryList ="";

             if (Session["Username"] != null)
             {
                 var role = Convert.ToInt16(Session["userrole"].ToString());
                 if (role == 1 || role == 3)
                 {
                     try
                     {
                         CategoryList =
                                         (from u in db.Categories

                                          select new CategorySetUpViewModel
                                          {
                                              CategoryID = u.CategoryID,
                                              CategoryName = u.CategoryName,
                                              CreatedBy = u.CreatedBy,
                                              CreatedOn = u.CreatedOn
                                          }).AsNoTracking().ToList();
                     }
                     catch (Exception ex)
                     {
                         ViewBag.DisplayMessage = "Info";
                         ModelState.AddModelError("", "Error: " + ex.Message);
                     }

                 }
                 else
                 {
                     return RedirectToAction("AdminLogin", "Users");
                 }
             }
             else
             {
                 return RedirectToAction("AdminLogin", "Users");
             }
            
            return View(CategoryList);
        }

        // GET: Category/Details/5
        public ActionResult Details(int? id)
        {
            object category = null;
            if (Session["Username"] != null)
            {
                var role = Convert.ToInt16(Session["userrole"].ToString());
                if (role == 1 || role == 3)
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    category  = db.Categories.Find(id);
                    if (category == null)
                    {
                        return HttpNotFound();
                    }
                }
                else
                {
                    return RedirectToAction("AdminLogin", "Users");
                }
            }
            else
            {
                return RedirectToAction("AdminLogin", "Users");
            }            
            return View(category);
        }

        // GET: Category/Create
        public ActionResult Add(int? id)
        {
            if (Session["Username"] != null)
            {
                var role = Convert.ToInt16(Session["userrole"].ToString());
                if (role == 1 || role == 3)
                {

                }
                else
                {
                    return RedirectToAction("AdminLogin", "Users");
                }
            }
            else
            {
                return RedirectToAction("AdminLogin", "Users");
            }
            return View();
        }

        // POST: Category/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add([Bind(Include = "CategoryID,CategoryName,CreatedBy,CreatedOn")] CategorySetUpViewModel catVM)
        {
            if (catVM.CategoryName != null)
            {
                try
                {
                    var addCategory = new Category
                    {
                        CategoryName = catVM.CategoryName,
                        CreatedBy = Session["username"].ToString(),
                        CreatedOn = DateTime.Now
                    };

                    db.Categories.Add(addCategory);
                    db.SaveChanges();
                    ViewBag.DisplayMessage = "success";
                    ModelState.AddModelError("", "Saved Successfully!");

                }
               catch(Exception ex)
                {
                    ViewBag.DisplayMessage = "Info";
                    ModelState.AddModelError("", "Error: " + ex.Message);
                }
               // return View(catVM);
            }

            return View(catVM);
        }

        // GET: Category/Edit/5
        public ActionResult Edit(int? id)
        {
            object category = null;
            if (Session["Username"] != null)
            {
                var role = Convert.ToInt16(Session["userrole"].ToString());
                if (role == 1 || role == 3)
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    category = db.Categories.Find(id);
                    if (category == null)
                    {
                        return HttpNotFound();
                    }
                }
                else
                {
                    return RedirectToAction("AdminLogin", "Users");
                }
            }
            else
            {
                return RedirectToAction("AdminLogin", "Users");
            }
            
            return View(category);
        }

        // POST: Category/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoryID,CategoryName,CreatedBy,CreatedOn")] Category category)
        {
            if (category.CategoryName != null)
            {
                try
                {
                    var categoryList = (from d in db.Categories.Where(x => x.CategoryID == category.CategoryID) select d).FirstOrDefault();
                    if (categoryList != null)
                    {
                        categoryList.CategoryName = category.CategoryName;
                        categoryList.CreatedBy = Session["username"].ToString();
                        categoryList.CreatedOn = DateTime.Now;
                        db.SaveChanges();
                        ViewBag.DisplayMessage = "success";
                        ModelState.AddModelError("", "Saved Successfully!");
                    }
                }
                catch(Exception ex)
                {
                    ViewBag.DisplayMessage = "Info";
                    ModelState.AddModelError("", "Error: " + ex.Message);
                }
               // return RedirectToAction("Show");
            }
            else
            {
                ViewBag.DisplayMessage = "Info";
                ModelState.AddModelError("", "Enter Category Name!");
            }
            return View(category);
        }

        // GET: Category/Delete/5
        public ActionResult Delete(int? id)
        {
            object categoryList = null;
            if (Session["Username"] != null)
            {
                
                var role = Convert.ToInt16(Session["userrole"].ToString());
                if (role == 1 || role == 3)
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                     categoryList = db.Categories.Find(id);
                    if (categoryList == null)
                    {
                        return HttpNotFound();
                    }
                }
                else
                {
                    return RedirectToAction("AdminLogin", "Users");
                }
            }
            else
            {
                return RedirectToAction("AdminLogin", "Users");
            }            
            return View(categoryList);
        }

        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            Category category = db.Categories.Find(id);
            try
            {
                db.Categories.Remove(category);
                db.SaveChanges();
                ViewBag.DisplayMessage = "success";
                ModelState.AddModelError("", "Deleted Successfully!");
            }
           catch(Exception ex)
            {
                ViewBag.DisplayMessage = "Info";
                ModelState.AddModelError("", "Error: " + ex.Message);
            }
            //return RedirectToAction("Show");
            return View(category);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineStore/Views/CategorySetUp/Add.cshtml
@model OnlineStore.CategorySetUpViewModel

@{
    ViewBag.Title = "Create";
    try
    {
        var role = Convert.ToInt16(Session["userrole"].ToString());
        if (role == 1)
        {
            Layout = "~/Views/Shared/AdminLayoutPage.cshtml";
        }       
        else if (role == 3)
        {
            Layout = "~/Views/Shared/DeveloperLayoutPage.cshtml";
        }
    }
    catch (Exception)
    {

    }
}


<div class="row">
    <div class="col-sm-2">
        <a href="@Url.Action("Showlist", "CategorySetUp")" class="demo btn btn-blue">
            <i class="fa fa-arrow-left">
            </i> | Back to list
        </a>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <i class="fa fa-external-link-square"></i>
        Add Category
        <div class="panel-tools">
            <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
            </a>

        </div>
    </div>
    <div class="panel-body">
        <form role="form" class="form-horizontal" method="POST">
            @if (ViewBag.DisplayMessage == "success")
            {
                if (ViewData.ModelState[""] != null)
                {
                    <div class="bs-example">
                        <div class="alert alert-success fade in">
                            <a href="#" class="close" data-dismiss="alert">×</a>
                            <strong>Success!</strong>@Html.ValidationSummary(true, "", new { @class = "text-success" })<br />
                        </div>
                    </div>
                }
            }
            else if (ViewBag.DisplayMessage == "Info")
            {
                if (ViewData.ModelState[""] != null)
                {
                    <div class="bs-example">
                        <div class="alert alert-danger fade in">
                            <a href="#" class="close" data-dismiss="alert">×</a>
                            <strong>Alert!</strong>@Html.ValidationSummary(true, "", new { @class = "text-danger" })<br />
                        </div>
                    </div>
                }
            }

            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                <hr />
                <div class="form-group">
                    @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>

            </div>
        </form>
    </div>
</div>

    <script>
    jQuery(document).ready(function () {
        Main.init();
        Index.init();
    });
    </script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OnlineStore/Views/CategorySetUp/Delete.cshtml
@model OnlineStore.Category

@{
    ViewBag.Title = "Delete";
    try
    {
        var role = Convert.ToInt16(Session["userrole"].ToString());
        if (role == 1)
        {
            Layout = "~/Views/Shared/AdminLayoutPage.cshtml";
        }
        
        else if (role == 3)
        {
            Layout = "~/Views/Shared/DeveloperLayoutPage.cshtml";
        }
    }
    catch (Exception)
    {

    }
}


    <script>
        jQuery(document).ready(function () {
            Main.init();
        });
    </script>


<div class="row">
    <div class="col-sm-2">        
        <a href="@Url.Action("Showlist", "CategorySetUp")" class="demo btn btn-blue">
            <i class="fa fa-arrow-left">
            </i> | Back to list
        </a>
    </div>  
</div>
<div class="panel">
    <div class="panel-heading">
        <i class="fa fa-external-link-square"></i>
        Are you sure you want to delete this?
        <div class="panel-tools">
            <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
            </a>

        </div>
    </div>
    <div class="panel-body">
        <form role="form" class="form-horizontal" method="POST">
            @if (ViewBag.DisplayMessage == "success")
            {
                if (ViewData.ModelState[""] != null)
                {
                    <div class="bs-example">
                        <div class="alert alert-success fade in">
                            <a href="#" class="close" data-dismiss="alert">×</a>
                            <strong>Success!</strong>@Html.ValidationSummary(true, "", new { @class = "text-success" })<br />
                        </div>
                    </div>
                }
            }
            else if (ViewBag.DisplayMessage == "Info")
            {
                if (ViewData.ModelState[""] != null)
                {
                    <div class="bs-example">
                        <div class="alert alert-danger fade in">
                            <a href="#" class="close" data-dismiss="alert">×</a>
                            <strong>Alert!</strong>@Html.ValidationSummary(true, "", new { @class = "text-danger" })<br />
                        </div>
                    </div>
                }
            }

            @Html.AntiForgeryToken()
            <div>

                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.CategoryName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CategoryName)
                        <hr />
                    </dd>
                </dl>               
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Delete" class="demo btn btn-red" onclick="return confirm('Are you sure you wish to delete this record?');" />
                </div>
            </div>
        </form>
    </div>
</div>

OnlineStore/Views/CategorySetUp/Details.cshtml
@model OnlineStore.Category

@{
    ViewBag.Title = "Details";
    try
    {
        var role = Convert.ToInt16(Session["userrole"].ToString());
        if (role == 1)
        {
            Layout = "~/Views/Shared/AdminLayoutPage.cshtml";
        }       
        else if (role == 3)
        {
            Layout = "~/Views/Shared/DeveloperLayoutPage.cshtml";
        }
    }
    catch (Exception)
    {

    }
}


    <script>
        jQuery(document).ready(function () {
            Main.init();
        });
    </script>

<div class="row">
    <div class="col-sm-2">
        <a href="@Url.Action("Showlist", "CategorySetUp")" class="demo btn btn-blue">
            <i class="fa fa-arrow-left">
            </i> | Back to list
        </a>
    </div>
</div>
<div class="panel">
    <div class="panel-heading">
        <i class="fa fa-external-link-square"></i>
        View category Details
        <div class="panel-tools">
            <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
            </a>

        </div>
    </div>
    <div class="panel-body">
        <form role="form" class="form-horizontal" method="POST">
           @if (ViewBag.DisplayMessage == "success")
           {
               if (ViewData.ModelState[""] != null)
               {
                <div class="bs-example">
                    <div class="alert alert-success fade in">
                        <a href="#" class="close" data-dismiss="alert">×</a>
                        <strong>Success!</strong>@Html.ValidationSummary(true, "", new { @class = "text-success" })<br />
                    </div>
                </div>
               }
           }
           else if (ViewBag.DisplayMessage == "Info")
           {
               if (ViewData.ModelState[""] != null)
               {
                <div class="bs-example">
                    <div class="alert alert-danger fade in">
                        <a href="#" class="close" data-dismiss="alert">×</a>
                        <strong>Alert!</strong>@Html.ValidationSummary(true, "", new { @class = "text-danger" })<br />
                    </div>
                </div>
               }
           }

            @Html.AntiForgeryToken()
            <div>

                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.CategoryName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CategoryName)
                        <hr />
                    </dd>
                </dl>
            </div>
        </form>
    </div>
</div>

OnlineStore/Views/CategorySetUp/Edit.cshtml
@model  Category

@{
    ViewBag.Title = "Edit";
    try
    {
        var role = Convert.ToInt16(Session["userrole"].ToString());
        if (role == 1)
        {
            Layout = "~/Views/Shared/AdminLayoutPage.cshtml";
        }
        
        else if (role == 3)
        {
            Layout = "~/Views/Shared/DeveloperLayoutPage.cshtml";
        }
    }
    catch (Exception)
    {

    }
}

   <script>
        jQuery(document).ready(function () {
            Main.init();
        });
    </script>


<div class="row">
    <div class="col-sm-2">
        <a href="@Url.Action("Showlist", "CategorySetUp")" class="demo btn btn-blue">
            <i class="fa fa-arrow-left">
            </i> | Back to list
        </a>
    </div>
</div>
<div class="panel">
    <div class="panel-heading">
        <i class="fa fa-external-link-square"></i>
        Edit Category
        <div class="panel-tools">
            <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
            </a>

        </div>
    </div>
    <div class="panel-body">
        <form role="form" class="form-horizontal" method="POST">
            @Html.AntiForgeryToken()
            @if (ViewBag.DisplayMessage == "success")
            {
                if (ViewData.ModelState[""] != null)
                {
                    <div class="bs-example">
                        <div class="alert alert-success fade in">
                            <a href="#" class="close" data-dismiss="alert">×</a>
                            <strong>Success!</strong>@Html.ValidationSummary(true, "", new { @class = "text-success" })<br />
                        </div>
                    </div>
                }
            }
            else if (ViewBag.DisplayMessage == "Info")
            {
                if (ViewData.ModelState[""] != null)
                {
                    <div class="bs-example">
                        <div class="alert alert-danger fade in">
                            <a href="#" class="close" data-dismiss="alert">×</a>
                            <strong>Alert!</strong>@Html.ValidationSummary(true, "", new { @class = "text-danger" })<br />
                        </div>
                    </div>
                }
            }
                    <div class="form-horizontal">

                        @Html.HiddenFor(model => model.CategoryID)

                        @*<div class="form-group">
                            @Html.LabelFor(model => model.CategoryID, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.CategoryID, new { htmlAttributes = new { @class = "form-control", @ReadOnly = false } })
                                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
                            </div>
                        </div>*@

                        <div class="form-group">
                            @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control", @ReadOnly = false } })
                                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.CreatedOn, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.CreatedOn, new { htmlAttributes = new { @class = "form-control", @ReadOnly = false } })
                                @Html.ValidationMessageFor(model => model.CreatedOn, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button type="submit" value="Save" id="btnSave" name="command" class="btn btn-primary">Update</button>
                            </div>
                        </div>
                    </div>
        </form>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OnlineStore/Views/CategorySetUp/ShowList.cshtml
@model IEnumerable<OnlineStore.CategorySetUpViewModel>

@{
    ViewBag.Title = "Index";
    try
    {
        var role = Convert.ToInt16(Session["userrole"].ToString());
        if (role == 1)
        {
            Layout = "~/Views/Shared/AdminLayoutPage.cshtml";
        }
        
        else if (role == 3)
        {
            Layout = "~/Views/Shared/DeveloperLayoutPage.cshtml";
        }
    }
    catch (Exception)
    {

    }
}

<div class="row">
    <div class="col-sm-2">
        <a href="@Url.Action("Add", "CategorySetUp")" class="demo btn btn-blue">
            <i class="fa fa-plus">
            </i> | Add New
        </a>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <i class="fa fa-external-link-square"></i> Category List
        <div class="panel-tools">
            <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
            </a>
            
        </div>
    </div>
    <div class="panel-body">
        <table class="table table-hover" id="sample-table-1">
            <thead>
                <tr>
                    @*<th>@Html.DisplayNameFor(model => model.CategoryID)</th>*@
                    <th>@Html.DisplayNameFor(model => model.CategoryName)</th>
                    <th>@Html.DisplayNameFor(model => model.CreatedBy)</th>
                    <th>@Html.DisplayNameFor(model => model.CreatedOn)</th>
                    <th>User Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        @*<td class="hidden-xs">
                            @Html.DisplayFor(modelItem => item.CategoryID)
                        </td>*@
                        <td class="hidden-xs">
                            @Html.DisplayFor(modelItem => item.CategoryName)
                        </td>
                        <td class="hidden-xs">
                            @Html.DisplayFor(modelItem => item.CreatedBy)
                        </td>
                        <td class="hidden-xs">
                            @Html.DisplayFor(modelItem => item.CreatedOn)
                        </td>

                        <td>
                            @*<a href="@Url.Action("edit", "category", new { id = item.CategoryID })" class="btn btn-xs btn-teal tooltips" data-placement="top" data-original-title="Edit"><i class="fa fa-edit"></i></a>*@
                            <a href="@Url.Action("details", "categorySetUp", new { id = item.CategoryID })" class="btn btn-xs btn-green tooltips" data-placement="top" data-original-title="View List"><i class="fa fa-eye"></i></a>
                            @*<a href="@Url.Action("Delete", "category", new { id = item.CategoryID })" class="btn btn-xs btn-bricky tooltips" data-placement="top" data-original-title="Delete"><i class="fa fa-trash-o"></i></a>*@
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

    <script>
            jQuery(document).ready(function() {
                Main.init();
            });
    </script>