OnlineStore/Controllers/SecurityQuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineStore;
using System.Web.Configuration;
using System.Net.Mail;
using System.Text;

namespace OnlineStore.Controllers
{
    public class SecurityQuestionsController : Controller
    {
        private OnlineStoreEntities db = new OnlineStoreEntities();
        PasswordHashing PwdHashing = new PasswordHashing();
        // GET: SecurityQuestions
        public ActionResult Show()
        {
            object sq = null;
            if (Session["Username"] != null)
            {
                var role = Convert.ToInt16(Session["userrole"].ToString());
                if (role == 3)
                {
                    sq = db.SecurityQuestions.ToList();
                }
                else
                {
                    return RedirectToAction("AdminLogin", "Users");
                }
            }
            else
            {
                return RedirectToAction("AdminLogin", "Users");
            }
            return View(sq);
        }

        // GET: SecurityQuestions/Details/5
        public ActionResult Details(int? id)
        {
            SecurityQuestion securityQuestion = null;
            if (Session["Username"] != null)
            {
                var role = Convert.ToInt16(Session["userrole"].ToString());
                if (role == 3)
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    securityQuestion = db.SecurityQuestions.Find(id);
                    if (securityQuestion == null)
                    {
                        return HttpNotFound();
                    }
                }
                else
                {
                    return RedirectToAction("AdminLogin", "Users");
                }
            }
            else
            {
                return RedirectToAction("AdminLogin", "Users");
            }
            
            return View(securityQuestion);
        }

        // GET: SecurityQuestions/Create
        public ActionResult Add()
        {
            if (Session["Username"] != null)
            {
                var role = Convert.ToInt16(Session["userrole"].ToString());
                if (role == 3)
                {

                }
                else
                {
                    return RedirectToAction("AdminLogin", "Users");
                }
            }
            else
            {
                return RedirectToAction("AdminLogin", "Users");
            }
            return View();
        }

        // POST: SecurityQuestions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add([Bind(Include = "SecurityQuestionID,Question")] SecurityQuestion securityQuestion)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var isExist = (from l in db.SecurityQuestions.Where(x => x.Question == securityQuestion.Question) select l).FirstOrDefault();
                     if (isExist == null)
                     {
                         db.SecurityQuestions.Add(securityQuestion);
                         db.SaveChanges();
                         // return RedirectToAction("Show");
                         ViewBag.DisplayMessage = "success";
                         ModelState.AddModelError("", "Question saved successfully!");
                     }
                     else
                     {
                         ViewBag.DisplayMessage = "Info";
                         ModelState.AddModelError("", "Security question " + isExist.Question + " already exist, Please enter a new question!");
                         //LoadDropDownList();
                     }
                }
                catch(Exception ex)
                {
                    ViewBag.DisplayMessage = "Info";
                    ModelState.AddModelError("", "Error!" + ex.Message);
                }
                
            }

            return View(securityQuestion);
        }

        // GET: SecurityQuestions/Edit/5
        public ActionResult Edit(int? id)
        {
            SecurityQuestion securityQuestion = null;
            if (Session["Username"] != null)
            {
                var role = Convert.ToInt16(Session["userrole"].ToString());
                if (role == 3)
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    securityQuestion = db.SecurityQuestions.Find(id);
                    if (securityQuestion == null)
                    {
                        return HttpNotFound();
                    }
                }
                else
                {
                    return RedirectToAction("AdminLogin", "Users");
                }
            }
            else
            {
                return RedirectToAction("AdminLogin", "Users");
            }
            
            return View(securityQuestion);
        }

        // POST: SecurityQuestions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SecurityQuestionID,Question")] SecurityQuestion securityQuestion)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(securityQuestion).State = EntityState.Modified;
                    db.SaveChanges();
                    ViewBag.DisplayMessage = "success";
                    ModelState.AddModelError("", "Question updated successfully!");
                }
                catch(Exception ex)
                {
                    ViewBag.DisplayMessage = "Info";
                    ModelState.AddModelError("", "Error!" + ex.Message);
                }
            }
            return View(securityQuestion);
        }

        // GET: SecurityQuestions/Delete/5
        public ActionResult Delete(int? id)
        {
            SecurityQuestion securityQuestion = null;
            if (Session["Username"] != null)
            {
                var role = Convert.ToInt16(Session["userrole"].ToString());
                if (role == 3)
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    securityQuestion = db.SecurityQuestions.Find(id);
                    if (securityQuestion == null)
                    {
                        return HttpNotFound();
                    }
                }
                else
                {
                    return RedirectToAction("AdminLogin", "Users");
                }
            }
            else
            {
                return RedirectToAction("AdminLogin", "Users");
            }
            
            return View(securityQuestion);
        }

        // POST: SecurityQuestions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                SecurityQuestion securityQuestion = db.SecurityQuestions.Find(id);
                db.SecurityQuestions.Remove(securityQuestion);
                db.SaveChanges();
                ViewBag.DisplayMessage = "success";
                ModelState.AddModelError("", "Security Question deleted successfully!");
                //return RedirectToAction("Show");
            }
           catch(Exception ex)
            {
                ViewBag.DisplayMessage = "Info";
                ModelState.AddModelError("", "Error!" + ex.Message);
            }
            return View();
        }

        


        public ActionResult SecurityQuestion()
        {
            if (Session["Username"] != null)
            {
                var role = Convert.ToInt16(Session["userrole"].ToString());
                if (role == 1 || role == 2 || role == 3)
                {
                    var sqtn = Session["username"].ToString();
                    try
                    {

                        var chkUser = (from l in db.Users
                                       join k in db.SecurityQuestions
                                           on l.SecurityQuestionID
                                           equals k.SecurityQuestionID
                                       where l.UserEmail == sqtn
                                       select new
                                       {
                                           l.UserLastName,
                                           l.UserFirstName,
                                           l.SecurityAnswer,
                                           k.Question
                                           //l.SecurityAnswer
                                       }).FirstOrDefault();
                        if (chkUser != null)
                        {
                            Session["firstname"] = chkUser.UserFirstName;
                            Session["SQ"] = chkUser.Question;
                            Session["SA"] = chkUser.SecurityAnswer;

                        }
                        //else
                        //{
                        //    ModelState.AddModelError("", "Security Answer not valid!");

OnlineStore/Views/SecurityQuestions/Add.cshtml
@model OnlineStore.SecurityQuestion

@{
    ViewBag.Title = "Create";
    try
    {
        var role = Convert.ToInt16(Session["userrole"].ToString());
        if (role == 1)
        {
            Layout = "~/Views/Shared/AdminLayoutPage.cshtml";
        }       
        else if (role == 3)
        {
            Layout = "~/Views/Shared/DeveloperLayoutPage.cshtml";
        }
    }
    catch (Exception)
    {

    }
}


<div class="row">
    <div class="col-sm-2">
        <a href="@Url.Action("Show", "SecurityQuestions")" class="demo btn btn-blue">
            <i class="fa fa-arrow-left">
            </i> | Back to list
        </a>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <i class="fa fa-external-link-square"></i>
        Add Security Question
        <div class="panel-tools">
            <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
            </a>

        </div>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm())
        {
            if (ViewBag.DisplayMessage == "success")
            { 
                if (ViewData.ModelState[""] != null)
                {
                    <div class="bs-example">
                        <div class="alert alert-success fade in">
                            <a href="#" class="close" data-dismiss="alert">×</a>
                            <strong>Success!</strong>@Html.ValidationSummary(true, "", new { @class = "text-success" })<br />
                        </div>
                    </div>
                }
            }
            else if (ViewBag.DisplayMessage == "Info")
            {
                if (ViewData.ModelState[""] != null)
                {
                    <div class="bs-example">
                        <div class="alert alert-danger fade in">
                            <a href="#" class="close" data-dismiss="alert">×</a>
                            <strong>Error!</strong>@Html.ValidationSummary(true, "", new { @class = "text-danger" })<br />
                        </div>
                    </div>
                }
            }

            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                <hr />
                <div class="form-group">
                    @Html.LabelFor(model => model.Question, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Question, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>

            </div>
        }
    </div>
</div>
    <script>
    jQuery(document).ready(function () {
        Main.init();
        Index.init();
    });
    </script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OnlineStore/Views/SecurityQuestions/Delete.cshtml
@model OnlineStore.SecurityQuestion

@{
    ViewBag.Title = "Delete";
    try
    {
        var role = Convert.ToInt16(Session["userrole"].ToString());
        if (role == 1)
        {
            Layout = "~/Views/Shared/AdminLayoutPage.cshtml";
        }        
        else if (role == 3)
        {
            Layout = "~/Views/Shared/DeveloperLayoutPage.cshtml";
        }
    }
    catch (Exception)
    {

    }
}
    <script>
        jQuery(document).ready(function () {
            Main.init();
        });
    </script>
<div class="row">
    <div class="col-sm-2">
        <a href="@Url.Action("Show", "SecurityQuestions")" class="demo btn btn-blue">
            <i class="fa fa-arrow-left">
            </i> | Back to list
        </a>
    </div>
</div>
<div class="panel">
    <div class="panel-heading">
        <i class="fa fa-external-link-square"></i>
        Are you sure you want to delete this?
        <div class="panel-tools">
            <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
            </a>

        </div>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm())
        {
            if (ViewBag.DisplayMessage == "success")
            {
                if (ViewData.ModelState[""] != null)
                {
                    <div class="bs-example">
                        <div class="alert alert-success fade in">
                            <a href="#" class="close" data-dismiss="alert">×</a>
                            <strong>Success!</strong>@Html.ValidationSummary(true, "", new { @class = "text-success" })<br />
                        </div>
                    </div>
                }
            }
            else if (ViewBag.DisplayMessage == "Info")
            {
                if (ViewData.ModelState[""] != null)
                {
                    <div class="bs-example">
                        <div class="alert alert-danger fade in">
                            <a href="#" class="close" data-dismiss="alert">×</a>
                            <strong>Error!</strong>@Html.ValidationSummary(true, "", new { @class = "text-danger" })<br />
                        </div>
                    </div>
                }
            }

            @Html.AntiForgeryToken()
            <div>

                <hr />
                <dl class="dl-horizontal">
                    @*<dt>
                        @Html.DisplayNameFor(model => model.Question)
                    </dt>*@

                    <dd>
                        @Html.DisplayFor(model => model.Question)
                    </dd>

                </dl>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Delete" class="demo btn btn-red" onclick="return confirm('Are you sure you wish to delete this record?');" />
                </div>
            </div>
        }
    </div>
</div>

OnlineStore/Views/SecurityQuestions/Details.cshtml
@model OnlineStore.SecurityQuestion

@{
    ViewBag.Title = "Details";
    try
    {
        var role = Convert.ToInt16(Session["userrole"].ToString());
        if (role == 1)
        {
            Layout = "~/Views/Shared/AdminLayoutPage.cshtml";
        }
        
        else if (role == 3)
        {
            Layout = "~/Views/Shared/DeveloperLayoutPage.cshtml";
        }
    }
    catch (Exception)
    {

    }
}
    <script>
        jQuery(document).ready(function () {
            Main.init();
        });
    </script>
<div class="row">
    <div class="col-sm-2">
        <a href="@Url.Action("Show", "SecurityQuestions")" class="demo btn btn-blue">
            <i class="fa fa-arrow-left">
            </i> | Back to list
        </a>
    </div>
</div>
<div class="panel">
    <div class="panel-heading">
        <i class="fa fa-external-link-square"></i>
        View Security Question
        <div class="panel-tools">
            <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
            </a>

        </div>
    </div>
    <div class="panel-body">
        <form role="form" class="form-horizontal" method="POST">
            @if (ViewBag.DisplayMessage == "success")
            {
                if (ViewData.ModelState[""] != null)
                {
                    <div class="bs-example">
                        <div class="alert alert-success fade in">
                            <a href="#" class="close" data-dismiss="alert">×</a>
                            <strong>Success!</strong>@Html.ValidationSummary(true, "", new { @class = "text-success" })<br />
                        </div>
                    </div>
                }
            }
            else if (ViewBag.DisplayMessage == "Info")
            {
                if (ViewData.ModelState[""] != null)
                {
                    <div class="bs-example">
                        <div class="alert alert-danger fade in">
                            <a href="#" class="close" data-dismiss="alert">×</a>
                            <strong>Alert!</strong>@Html.ValidationSummary(true, "", new { @class = "text-danger" })<br />
                        </div>
                    </div>
                }
            }

            @Html.AntiForgeryToken()
            <div>

                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Question)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Question)
                    </dd>

                </dl>
            </div>
        </form>
    </div>
</div>

OnlineStore/Views/SecurityQuestions/Edit.cshtml
@model OnlineStore.SecurityQuestion

@{
    ViewBag.Title = "Edit";
    try
    {
        var role = Convert.ToInt16(Session["userrole"].ToString());
        if (role == 1)
        {
            Layout = "~/Views/Shared/AdminLayoutPage.cshtml";
        }
       
        else if (role == 3)
        {
            Layout = "~/Views/Shared/DeveloperLayoutPage.cshtml";
        }
    }
    catch (Exception)
    {

    }
}
    <script>
        jQuery(document).ready(function () {
            Main.init();
        });
    </script>
<div class="row">
    <div class="col-sm-2">
        <a href="@Url.Action("Show", "SecurityQuestions")" class="demo btn btn-blue">
            <i class="fa fa-arrow-left">
            </i> | Back to list
        </a>
    </div>
</div>
<div class="panel">
    <div class="panel-heading">
        <i class="fa fa-external-link-square"></i>
        Edit Security Question
        <div class="panel-tools">
            <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
            </a>

        </div>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
           
            if (ViewBag.DisplayMessage == "success")
            {
                if (ViewData.ModelState[""] != null)
                {
                    <div class="bs-example">
                        <div class="alert alert-success fade in">
                            <a href="#" class="close" data-dismiss="alert">×</a>
                            <strong>Success!</strong>@Html.ValidationSummary(true, "", new { @class = "text-success" })<br />
                        </div>
                    </div>
                }
            }
            else if (ViewBag.DisplayMessage == "Info")
            {
                if (ViewData.ModelState[""] != null)
                {
                    <div class="bs-example">
                        <div class="alert alert-danger fade in">
                            <a href="#" class="close" data-dismiss="alert">×</a>
                            <strong>Error!</strong>@Html.ValidationSummary(true, "", new { @class = "text-danger" })<br />
                        </div>
                    </div>
                }
            }
                    <div class="form-horizontal">
                        @Html.HiddenFor(model => model.SecurityQuestionID)

                        <div class="form-group">
                            @Html.LabelFor(model => model.Question, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Question, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
                            </div>
                        </div>                        
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button type="submit" value="Save" id="btnSave" name="command" class="btn btn-primary">Update</button>
                            </div>
                        </div>
                    </div>
        }
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OnlineStore/Views/SecurityQuestions/ForgetSecurityAnswer.cshtml
@{
    ViewBag.Title = "ForgetSecurityAnswer";
    Layout = "~/Views/Shared/LoginRegisterLayoutPage.cshtml";
}

<body class="login example2">

    <div class="main-login col-sm-4 col-sm-offset-4">
        <div class="logo">
            @*CLIP<i class="clip-clip"></i>ONE*@
            <img src="~/Images/Logo.png" alt="glorious evidence logo" />
        </div>
        <!-- start: LOGIN BOX -->
        <div class="box-login">
            <h3>Security Question Reset Request</h3>
            <p>
                Please enter your email address to get system-generated security answer.
            </p>
            @using (Html.BeginForm())
            {
                if (ViewBag.DisplayMessage == "success")
                {
                    if (ViewData.ModelState[""] != null)
                    {
                        <div class="bs-example">
                            <div class="alert alert-success fade in">
                                <a href="#" class="close" data-dismiss="alert">×</a>
                                <strong>Success!</strong>@Html.ValidationSummary(true, "", new { @class = "text-success" })<br />
                            </div>
                        </div>
                    }
                }
                else if (ViewBag.DisplayMessage == "Info")
                {
                    if (ViewData.ModelState[""] != null)
                    {
                        <div class="bs-example">
                            <div class="alert alert-danger fade in">
                                <a href="#" class="close" data-dismiss="alert">×</a>
                                <strong>Alert!</strong>@Html.ValidationSummary(true, "", new { @class = "text-danger" })<br />
                            </div>
                        </div>
                    }
                }
                <div class="errorHandler alert alert-danger no-display">
                    <i class="fa fa-remove-sign"></i> You have some form errors. Please check below.
                </div>
                <fieldset>
                    <div class="form-group">
                        <span class="input-icon">
                            <input type="text" class="form-control" name="emailAddress" placeholder="Email Address" required>
                            <i class="fa fa-envelope"></i>
                            <a class="forgot" href="@Url.Action("SecurityQuestion", "SecurityQuestions")">
                                Return to Security Question
                            </a>
                        </span>
                    </div>

                    <div class="form-actions">

                        <button type="submit" class="btn btn-bricky pull-right">
                            Submit <i class="fa fa-arrow-circle-right"></i>
                        </button>
                    </div>
                    <div class="new-account">
                        @*Don't have an account yet?
                            <a href="#" class="register">
                                Create an account
                            </a>*@
                    </div>
                </fieldset>
            }
        </div>
        <!-- end: LOGIN BOX -->
        <!-- start: COPYRIGHT -->
        <div class="copyright">
            Glorious Evidence Ltd &copy; @DateTime.Now.Year | All Rights Reserved.
        </div>
        <!-- end: COPYRIGHT -->
    </div>
</body>

<!-- start: MAIN JAVASCRIPTS -->
<!--[if lt IE 9]>
        <script src="@Url.Content("~/bower_components/respond/dest/respond.min.js")"></script>
        <script src="@Url.Content("~/bower_components/Flot/excanvas.min.js")"></script>
        <script src="@Url.Content("~/bower_components/jquery-1.x/dist/jquery.min.js")"></script>
        <![endif]-->
<!--[if gte IE 9]><!-->
<!-- build:script resurces.jQuery --><!-- /build -->
<!--<![endif]-->
<!-- build:script bundle --><!-- /build -->
<!-- build:script main --><!-- /build -->
<!-- end: MAIN JAVASCRIPTS -->
<!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
<script src="@Url.Content("~/bower_components/jquery-validation/dist/jquery.validate.min.js")"></script>
<script src="@Url.Content("~/assets/js/min/login.min.js")"></script>
<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->

<script>
    jQuery(document).ready(function () {
        Main.init();
        Login.init();
    });
</script>

OnlineStore/Views/SecurityQuestions/Show.cshtml
@model IEnumerable<OnlineStore.SecurityQuestion>

@{
    ViewBag.Title = "Index";
    try
    {
        var role = Convert.ToInt16(Session["userrole"].ToString());
        if (role == 1)
        {
            Layout = "~/Views/Shared/AdminLayoutPage.cshtml";
        }      
        else if (role == 3)
        {
            Layout = "~/Views/Shared/DeveloperLayoutPage.cshtml";
        }
    }
    catch (Exception)
    {

    }
}


@*<p>
    <a href="/SecurityQuestions/Add" class="demo btn btn-blue">
        <i class="fa fa-plus"></i> | Add New
    </a>
</p>*@

<div class="row">
    <div class="col-sm-2">
        <a href="@Url.Action("Add", "SecurityQuestions")" class="demo btn btn-blue">
            <i class="fa fa-plus">
            </i> | Add New
        </a>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <i class="fa fa-external-link-square"></i> Security Question List
        <div class="panel-tools">
            <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
            </a>

        </div>
    </div>
    <div class="panel-body">
        <table class="table table-hover" id="sample-table-1">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Question)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Question)
                        </td>
                        <td>
                            <a href="@Url.Action("edit", "securityQuestions", new { id = item.SecurityQuestionID })" class="btn btn-xs btn-teal tooltips" data-placement="top" data-original-title="Edit"><i class="fa fa-edit"></i></a>
                            <a href="@Url.Action("details", "securityQuestions", new { id = item.SecurityQuestionID })" class="btn btn-xs btn-green tooltips" data-placement="top" data-original-title="View List"><i class="fa fa-eye"></i></a>
                            <a href="@Url.Action("delete", "securityQuestions", new { id = item.SecurityQuestionID })" class="btn btn-xs btn-bricky tooltips" data-placement="top" data-original-title="Delete"><i class="fa fa-trash-o"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

    <script>
        jQuery(document).ready(function() {
            Main.init();
        });
    </script>