OnlineStore/Controllers/SubCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineStore;

namespace OnlineStore.Controllers
{
    public class SubCategoriesController : Controller
    {
        private OnlineStoreEntities db = new OnlineStoreEntities();

        // GET: SubCategories
        public ActionResult Show()
        {
            object subCategoryList = "";
            if (Session["Username"] != null)
            {
                var role = Convert.ToInt16(Session["userrole"].ToString());
                if (role == 1 || role == 3)
                {
                    try
                    {
                        subCategoryList =
                                        (from u in db.SubCategories
                                         join ct in db.Categories
                                on u.CategoryID equals ct.CategoryID

                                         select new SubCategoryViewModel
                                         {
                                             SubCategoryID = u.SubCategoryID,
                                             CategoryName = ct.CategoryName,
                                             SubCategoryName = u.SubCategoryName,
                                             CreatedBy = u.CreatedBy,
                                             CreatedOn = u.CreatedOn
                                         }).ToList();
                    }
                    catch (Exception ex)
                    {
                        ViewBag.DisplayMessage = "Info";
                        ModelState.AddModelError("", "Error: " + ex.Message);
                    }
                }
                else
                {
                    return RedirectToAction("AdminLogin", "Users");
                }
            }
            else
            {
                return RedirectToAction("AdminLogin", "Users");
            }
            
            return View(subCategoryList);

            //return View(subCategories);
        }

        // GET: SubCategories/Details/5
        public ActionResult Details(int? id)
        {         
            object subCategoryList = "";
            if (Session["Username"] != null)
            {
                var role = Convert.ToInt16(Session["userrole"].ToString());
                if (role == 1 || role == 3)
                {
                    try
                    {
                        subCategoryList =
                                        (from u in db.SubCategories
                                         join ct in db.Categories
                                on u.CategoryID equals ct.CategoryID
                                         where u.SubCategoryID == id
                                         select new SubCategoryViewModel
                                         {
                                             SubCategoryID = u.SubCategoryID,
                                             CategoryName = ct.CategoryName,
                                             SubCategoryName = u.SubCategoryName,
                                             CreatedBy = u.CreatedBy,
                                             CreatedOn = u.CreatedOn
                                         }).FirstOrDefault();
                    }
                    catch (Exception ex)
                    {
                        ViewBag.DisplayMessage = "Info";
                        ModelState.AddModelError("", "Error: " + ex.Message);
                    }
                }
                else
                {
                    return RedirectToAction("AdminLogin", "Users");
                }
            }
            else
            {
                return RedirectToAction("AdminLogin", "Users");
            }
            
            return View(subCategoryList);
        }

        // GET: SubCategories/Create
        public ActionResult Add()
        {
            if (Session["Username"] != null)
            {
                var role = Convert.ToInt16(Session["userrole"].ToString());
                if (role == 1 || role == 3)
                {
                    LoadDropDownList();
                }
                else
                {
                    return RedirectToAction("AdminLogin", "Users");
                }
            }
            else
            {
                return RedirectToAction("AdminLogin", "Users");
            }           
            return View();
        }

        // POST: SubCategories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add([Bind(Include = "SubCategoryID,CategoryID,CreatedBy,CreatedOn,SubCategoryName")] SubCategoryViewModel subCat)
        {
           
            try
            {
                var subCategoryAdd = new SubCategory
                {
                    CategoryID = Convert.ToInt16(subCat.CategoryID.ToString()),
                    SubCategoryName = subCat.SubCategoryName,
                    CreatedBy = Session["username"].ToString(),
                    CreatedOn = DateTime.Now,
                };

                var isExist = (from l in db.SubCategories.Where(x => x.SubCategoryName == subCat.SubCategoryName) select l).FirstOrDefault();
                if (isExist == null)
                {
                    db.SubCategories.Add(subCategoryAdd);
                    db.SaveChanges();

                    ViewBag.DisplayMessage = "success";
                    ModelState.AddModelError("", "Saved Successfully!");
                    LoadDropDownList();
                }
                else
                {
                    ViewBag.DisplayMessage = "Info";
                    ModelState.AddModelError("", "Sub-Category Name " + isExist.SubCategoryName + " already exist, Please enter a new Sub-Category Name!");
                    LoadDropDownList();
                }
            }
            catch(Exception ex)
            {
                ViewBag.DisplayMessage = "Info";
                ModelState.AddModelError("", "Error: " + ex.Message);
            }
            return View();
        }

        // GET: SubCategories/Edit/5
        public ActionResult Edit(int? id)
        {
            object subCategoryList = "";
            if (Session["Username"] != null)
            {
                var role = Convert.ToInt16(Session["userrole"].ToString());
                if (role == 1 || role == 3)
                {
                    try
                    {
                        subCategoryList =
                                        (from u in db.SubCategories
                                         join ct in db.Categories
                                on u.CategoryID equals ct.CategoryID
                                         where u.SubCategoryID == id
                                         select new SubCategoryViewModel
                                         {
                                             SubCategoryID = u.SubCategoryID,
                                             CategoryName = ct.CategoryName,
                                             SubCategoryName = u.SubCategoryName,
                                             CreatedBy = u.CreatedBy,
                                             CreatedOn = u.CreatedOn
                                         }).FirstOrDefault();
                    }
                    catch (Exception ex)
                    {
                        ViewBag.DisplayMessage = "Info";
                        ModelState.AddModelError("", "Error: " + ex.Message);
                    }
                }
                else
                {
                    return RedirectToAction("AdminLogin", "Users");
                }
            }
            else
            {
                return RedirectToAction("AdminLogin", "Users");
            }
           
            return View(subCategoryList);
        }

        // POST: SubCategories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SubCategoryID,CategoryID,CreatedBy,CreatedOn,SubCategoryName")] SubCategoryViewModel subCat)
        {
            if (subCat.SubCategoryName != null)
            {
                try
                {
                    var subCategoryList = (from d in db.SubCategories.Where(x => x.SubCategoryID == subCat.SubCategoryID) select d).FirstOrDefault();
                    if (subCategoryList != null)
                    {
                        subCategoryList.SubCategoryName = subCat.SubCategoryName;
                        subCategoryList.CreatedBy = Session["username"].ToString();
                        subCategoryList.CreatedOn = DateTime.Now;
                        db.SaveChanges();
                        ViewBag.DisplayMessage = "success";
                        ModelState.AddModelError("", "Updated Successfully!");
                    }
                }
                catch(Exception ex)
                {
                    ViewBag.DisplayMessage = "Info";
                    ModelState.AddModelError("", "Error: " + ex.Message);
                }
                //return RedirectToAction("Show");
            }
            else
            {
                ViewBag.DisplayMessage = "Info";
                ModelState.AddModelError("", "Enter Category Name!");
            }
            return View(subCat);
        }

        // GET: SubCategories/Delete/5
        public ActionResult Delete(int? id)

OnlineStore/Views/SubCategories/Add.cshtml
@model OnlineStore.SubCategoryViewModel

@{
    ViewBag.Title = "Create";
    try
    {
        var role = Convert.ToInt16(Session["userrole"].ToString());
        if (role == 1)
        {
            Layout = "~/Views/Shared/AdminLayoutPage.cshtml";
        }
        
        else if (role == 3)
        {
            Layout = "~/Views/Shared/DeveloperLayoutPage.cshtml";
        }
    }
    catch (Exception)
    {

    }
}

<div class="row">
    <div class="col-sm-2">
        <a href="@Url.Action("Show", "SubCategories")" class="demo btn btn-blue">
            <i class="fa fa-arrow-left">
            </i> | Back to list
        </a>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <i class="fa fa-external-link-square"></i>
        Add Sub Category
        <div class="panel-tools">
            <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
            </a>

        </div>
    </div>
    <div class="panel-body">
        <form role="form" class="form-horizontal" method="POST">
            @if (ViewBag.DisplayMessage == "success")
            {
                if (ViewData.ModelState[""] != null)
                {
                    <div class="bs-example">
                        <div class="alert alert-success fade in">
                            <a href="#" class="close" data-dismiss="alert">×</a>
                            <strong>Success!</strong>@Html.ValidationSummary(true, "", new { @class = "text-success" })<br />
                        </div>
                    </div>
                }
            }
            else if (ViewBag.DisplayMessage == "Info")
            {
                if (ViewData.ModelState[""] != null)
                {
                    <div class="bs-example">
                        <div class="alert alert-danger fade in">
                            <a href="#" class="close" data-dismiss="alert">×</a>
                            <strong>Alert!</strong>@Html.ValidationSummary(true, "", new { @class = "text-danger" })<br />
                        </div>
                    </div>
                }
            }

            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                <hr />

                <div class="form-group">
                    @Html.LabelFor(model => model.CategoryID, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @*@Html.EditorFor(model => model.MaritalStatus, new { htmlAttributes = new { @class = "form-control" } })*@
                        @Html.DropDownListFor(model => model.CategoryID, (IEnumerable<SelectListItem>)ViewBag.fkCategoryList, "---Select---", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SubCategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SubCategoryName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SubCategoryName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
            </div>      
        </form>
    </div>
</div>
    <script>
    jQuery(document).ready(function () {
        Main.init();
        Index.init();
    });
    </script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OnlineStore/Views/SubCategories/Delete.cshtml
@model OnlineStore.SubCategoryViewModel

@{
    ViewBag.Title = "Delete";
    try
    {
        var role = Convert.ToInt16(Session["userrole"].ToString());
        if (role == 1)
        {
            Layout = "~/Views/Shared/AdminLayoutPage.cshtml";
        }
        
        else if (role == 3)
        {
            Layout = "~/Views/Shared/DeveloperLayoutPage.cshtml";
        }
    }
    catch (Exception)
    {

    }
}
    <script>
        jQuery(document).ready(function () {
            Main.init();
        });
    </script>
<div class="row">
    <div class="col-sm-2">
        <a href="@Url.Action("Show", "SubCategories")" class="demo btn btn-blue">
            <i class="fa fa-arrow-left">
            </i> | Back to list
        </a>
    </div>
</div>
<div class="panel">
    <div class="panel-heading">
        <i class="fa fa-external-link-square"></i>
        Are you sure you want to delete this?
        <div class="panel-tools">
            <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
            </a>

        </div>
    </div>
    <div class="panel-body">
        <form role="form" class="form-horizontal" method="POST">
            @if (ViewBag.DisplayMessage == "success")
            {
                if (ViewData.ModelState[""] != null)
                {
                    <div class="bs-example">
                        <div class="alert alert-success fade in">
                            <a href="#" class="close" data-dismiss="alert">×</a>
                            <strong>Success!</strong>@Html.ValidationSummary(true, "", new { @class = "text-success" })<br />
                        </div>
                    </div>
                }
            }
            else if (ViewBag.DisplayMessage == "Info")
            {
                if (ViewData.ModelState[""] != null)
                {
                    <div class="bs-example">
                        <div class="alert alert-danger fade in">
                            <a href="#" class="close" data-dismiss="alert">×</a>
                            <strong>Alert!</strong>@Html.ValidationSummary(true, "", new { @class = "text-danger" })<br />
                        </div>
                    </div>
                }
            }

            @Html.AntiForgeryToken()
            <div>

                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.CreatedBy)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CreatedBy)
                        <hr />
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.CreatedOn)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CreatedOn)
                        <hr />
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.SubCategoryName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.SubCategoryName)
                        <hr />
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.CategoryName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CategoryName)
                        <hr />
                    </dd>
                </dl>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Delete" class="demo btn btn-red" onclick="return confirm('Are you sure you wish to delete this record?');" />
                </div>
            </div>
        </form>
    </div>
</div>

OnlineStore/Views/SubCategories/Details.cshtml
@model OnlineStore.SubCategoryViewModel

@{
    ViewBag.Title = "Details";
    try
    {
        var role = Convert.ToInt16(Session["userrole"].ToString());
        if (role == 1)
        {
            Layout = "~/Views/Shared/AdminLayoutPage.cshtml";
        }        
        else if (role == 3)
        {
            Layout = "~/Views/Shared/DeveloperLayoutPage.cshtml";
        }
    }
    catch (Exception)
    {

    }
}
    <script>
        jQuery(document).ready(function () {
            Main.init();
        });
    </script>
<div class="row">
    <div class="col-sm-2">
        <a href="@Url.Action("Show", "SubCategories")" class="demo btn btn-blue">
            <i class="fa fa-arrow-left">
            </i> | Back to list
        </a>
    </div>
</div>
<div class="panel">
    <div class="panel-heading">
        <i class="fa fa-external-link-square"></i>
        View Sub Category Details
        <div class="panel-tools">
            <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
            </a>

        </div>
    </div>
    <div class="panel-body">
        <form role="form" class="form-horizontal" method="POST">
            @if (ViewBag.DisplayMessage == "success")
            {
                if (ViewData.ModelState[""] != null)
                {
                    <div class="bs-example">
                        <div class="alert alert-success fade in">
                            <a href="#" class="close" data-dismiss="alert">×</a>
                            <strong>Success!</strong>@Html.ValidationSummary(true, "", new { @class = "text-success" })<br />
                        </div>
                    </div>
                }
            }
            else if (ViewBag.DisplayMessage == "Info")
            {
                if (ViewData.ModelState[""] != null)
                {
                    <div class="bs-example">
                        <div class="alert alert-danger fade in">
                            <a href="#" class="close" data-dismiss="alert">×</a>
                            <strong>Alert!</strong>@Html.ValidationSummary(true, "", new { @class = "text-danger" })<br />
                        </div>
                    </div>
                }
            }

            @Html.AntiForgeryToken()
            <div>

                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.CreatedBy)
                        
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CreatedBy)
                        <hr />
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.CreatedOn)
                        
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CreatedOn)
                        <hr />
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.SubCategoryName)
                        
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.SubCategoryName)
                        <hr />
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.CategoryName)
                       
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CategoryName)
                        <hr />
                    </dd>
                </dl>
            </div>
        </form>
    </div>
</div>

OnlineStore/Views/SubCategories/Edit.cshtml
@model OnlineStore.SubCategoryViewModel

@{
    ViewBag.Title = "Edit";
    try
    {
        var role = Convert.ToInt16(Session["userrole"].ToString());
        if (role == 1)
        {
            Layout = "~/Views/Shared/AdminLayoutPage.cshtml";
        }       
        else if (role == 3)
        {
            Layout = "~/Views/Shared/DeveloperLayoutPage.cshtml";
        }
    }
    catch (Exception)
    {

    }
}
    <script>
        jQuery(document).ready(function () {
            Main.init();
        });
    </script>
<div class="row">
    <div class="col-sm-2">
        <a href="@Url.Action("Show", "SubCategories")" class="demo btn btn-blue">
            <i class="fa fa-arrow-left">
            </i> | Back to list
        </a>
    </div>
</div>
<div class="panel">
    <div class="panel-heading">
        <i class="fa fa-external-link-square"></i>
        Edit Sub Category
        <div class="panel-tools">
            <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
            </a>

        </div>
    </div>
    <div class="panel-body">
        <form role="form" class="form-horizontal" method="POST">
            
            @if (ViewBag.DisplayMessage == "success")
            {
                if (ViewData.ModelState[""] != null)
                {
                    <div class="bs-example">
                        <div class="alert alert-success fade in">
                            <a href="#" class="close" data-dismiss="alert">×</a>
                            <strong>Success!</strong>@Html.ValidationSummary(true, "", new { @class = "text-success" })<br />
                        </div>
                    </div>
                }
            }
            else if (ViewBag.DisplayMessage == "Info")
            {
                if (ViewData.ModelState[""] != null)
                {
                    <div class="bs-example">
                        <div class="alert alert-danger fade in">
                            <a href="#" class="close" data-dismiss="alert">×</a>
                            <strong>Alert!</strong>@Html.ValidationSummary(true, "", new { @class = "text-danger" })<br />
                        </div>
                    </div>
                }
            }
            @Html.AntiForgeryToken()
            <div class="form-horizontal">

                @Html.HiddenFor(model => model.CategoryID)

                @Html.HiddenFor(model => model.SubCategoryID)

                @Html.HiddenFor(model => model.CategoryID)

                <div class="form-group">
                    @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control", @ReadOnly = true } })
                        @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CreatedOn, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CreatedOn, new { htmlAttributes = new { @class = "form-control", @ReadOnly = true } })
                        @Html.ValidationMessageFor(model => model.CreatedOn, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SubCategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SubCategoryName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SubCategoryName, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit" value="Save" id="btnSave" name="command" class="btn btn-primary">Update</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OnlineStore/Views/SubCategories/Show.cshtml
@model IEnumerable<OnlineStore.SubCategoryViewModel>

@{
    ViewBag.Title = "Index";
    try
    {
        var role = Convert.ToInt16(Session["userrole"].ToString());
        if (role == 1)
        {
            Layout = "~/Views/Shared/AdminLayoutPage.cshtml";
        }        
        else if (role == 3)
        {
            Layout = "~/Views/Shared/DeveloperLayoutPage.cshtml";
        }
    }
    catch (Exception)
    {

    }
}


<!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
<link type="text/css" rel="stylesheet" href="@Url.Content("~/bower_components/select2/dist/css/select2.min.css")" />
<link type="text/css" rel="stylesheet" href="@Url.Content("~/bower_components/datatables/media/css/dataTables.bootstrap.min.css")" />
<!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
<!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
<script type="text/javascript" src="@Url.Content("~/bower_components/bootbox.js/bootbox.js")"></script>
<script type="text/javascript" src="@Url.Content("~/bower_components/jquery-mockjax/dist/jquery.mockjax.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/bower_components/select2/dist/js/select2.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/bower_components/datatables/media/js/jquery.dataTables.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/bower_components/datatables/media/js/dataTables.bootstrap.js")"></script>
<script type="text/javascript" src="@Url.Content("~/assets/js/min/table-data.min.js")"></script>
<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->

<script type="text/javascript">
    jQuery(document).ready(function () {
        Main.init();
        TableData.init();
    });
</script>


<div class="row">
    <div class="col-sm-2">
        <a href="@Url.Action("Add", "SubCategories")" class="demo btn btn-blue">
            <i class="fa fa-plus">
            </i> | Add New
        </a>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <i class="fa fa-external-link-square"></i> SubCategory List
        <div class="panel-tools">
            <a class="btn btn-xs btn-link panel-collapse collapses" href="#"> </a>
        </div>
    </div>
    <div class="panel-body">
        <div class="dataTables_wrapper form-inline dt-bootstrap no-footer" id="sample_1_wrapper">
            <div class="row">
                <div class="col-sm-12">
                    <table aria-describedby="sample_1_info" role="grid" class="table table-striped table-bordered table-hover table-full-width dataTable no-footer" id="sample_1">
                        <thead>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.CategoryName)</th>
                                <th>@Html.DisplayNameFor(model => model.SubCategoryName)</th>
                                <th>@Html.DisplayNameFor(model => model.CreatedBy)</th>
                                <th>@Html.DisplayNameFor(model => model.CreatedOn)</th>
                                <th>User Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td class="hidden-xs">
                                        @Html.DisplayFor(modelItem => item.CategoryName)
                                    </td>
                                    <td class="hidden-xs">
                                        @Html.DisplayFor(modelItem => item.SubCategoryName)
                                    </td>
                                    <td class="hidden-xs">
                                        @Html.DisplayFor(modelItem => item.CreatedBy)
                                    </td>
                                    <td class="hidden-xs">
                                        @Html.DisplayFor(modelItem => item.CreatedOn)
                                    </td>

                                    <td>
                                        <a href="@Url.Action("edit", "subcategories", new { id = item.SubCategoryID })" class="btn btn-xs btn-teal tooltips" data-placement="top" data-original-title="Edit"><i class="fa fa-edit"></i></a>
                                        <a href="@Url.Action("details", "subcategories", new { id = item.SubCategoryID })" class="btn btn-xs btn-green tooltips" data-placement="top" data-original-title="View List"><i class="fa fa-eye"></i></a>
                                        <a href="@Url.Action("Delete", "subcategories", new { id = item.SubCategoryID })" class="btn btn-xs btn-bricky tooltips" data-placement="top" data-original-title="Delete"><i class="fa fa-trash-o"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>